### ISSUE TITLE
请问你是如何制作键盘的图片的效果的

### ISSUE THREAD

**Issue by JayChou404** [xiongyihui/keyboard#2]
我添加了几个功能, 我想制作键盘效果演示

**Comment by JayChou404** [comment]
已解决, 键盘效果制作可以使用这个网站:http://www.keyboard-layout-editor.com/

**Comment by JakeZhou0** [comment]
已解决, 键盘效果制作可以使用这个网站:http://www.keyboard-layout-editor.com/
